# Generated by Django 2.2.4 on 2019-08-12 10:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailinglist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MialingList',
            new_name='MailingList',
        ),
    ]
